version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dolar-colombia-gov"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13dkeo1s5gxga"
s3_prefix = "dolar-colombia-gov"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
